# Generated by Django 4.2.11 on 2024-04-05 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('tournoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tournoi')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.PositiveIntegerField()),
                ('score2', models.PositiveIntegerField()),
                ('gagnant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_gagnes', to='app.participant')),
                ('participant1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_participant1', to='app.participant')),
                ('participant2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_participant2', to='app.participant')),
                ('tournoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tournoi')),
            ],
        ),
    ]
